// Generated by gencpp from file mia_hand_msgs/ConnectSerial.msg
// DO NOT EDIT!


#ifndef MIA_HAND_MSGS_MESSAGE_CONNECTSERIAL_H
#define MIA_HAND_MSGS_MESSAGE_CONNECTSERIAL_H

#include <ros/service_traits.h>


#include <mia_hand_msgs/ConnectSerialRequest.h>
#include <mia_hand_msgs/ConnectSerialResponse.h>


namespace mia_hand_msgs
{

struct ConnectSerial
{

typedef ConnectSerialRequest Request;
typedef ConnectSerialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConnectSerial
} // namespace mia_hand_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mia_hand_msgs::ConnectSerial > {
  static const char* value()
  {
    return "86e89cea09faaef62a0ac1903573e480";
  }

  static const char* value(const ::mia_hand_msgs::ConnectSerial&) { return value(); }
};

template<>
struct DataType< ::mia_hand_msgs::ConnectSerial > {
  static const char* value()
  {
    return "mia_hand_msgs/ConnectSerial";
  }

  static const char* value(const ::mia_hand_msgs::ConnectSerial&) { return value(); }
};


// service_traits::MD5Sum< ::mia_hand_msgs::ConnectSerialRequest> should match
// service_traits::MD5Sum< ::mia_hand_msgs::ConnectSerial >
template<>
struct MD5Sum< ::mia_hand_msgs::ConnectSerialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mia_hand_msgs::ConnectSerial >::value();
  }
  static const char* value(const ::mia_hand_msgs::ConnectSerialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mia_hand_msgs::ConnectSerialRequest> should match
// service_traits::DataType< ::mia_hand_msgs::ConnectSerial >
template<>
struct DataType< ::mia_hand_msgs::ConnectSerialRequest>
{
  static const char* value()
  {
    return DataType< ::mia_hand_msgs::ConnectSerial >::value();
  }
  static const char* value(const ::mia_hand_msgs::ConnectSerialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mia_hand_msgs::ConnectSerialResponse> should match
// service_traits::MD5Sum< ::mia_hand_msgs::ConnectSerial >
template<>
struct MD5Sum< ::mia_hand_msgs::ConnectSerialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mia_hand_msgs::ConnectSerial >::value();
  }
  static const char* value(const ::mia_hand_msgs::ConnectSerialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mia_hand_msgs::ConnectSerialResponse> should match
// service_traits::DataType< ::mia_hand_msgs::ConnectSerial >
template<>
struct DataType< ::mia_hand_msgs::ConnectSerialResponse>
{
  static const char* value()
  {
    return DataType< ::mia_hand_msgs::ConnectSerial >::value();
  }
  static const char* value(const ::mia_hand_msgs::ConnectSerialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIA_HAND_MSGS_MESSAGE_CONNECTSERIAL_H
