// Generated by gencpp from file mia_hand_msgs/FingersData.msg
// DO NOT EDIT!


#ifndef MIA_HAND_MSGS_MESSAGE_FINGERSDATA_H
#define MIA_HAND_MSGS_MESSAGE_FINGERSDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mia_hand_msgs
{
template <class ContainerAllocator>
struct FingersData_
{
  typedef FingersData_<ContainerAllocator> Type;

  FingersData_()
    : thu(0)
    , ind(0)
    , mrl(0)  {
    }
  FingersData_(const ContainerAllocator& _alloc)
    : thu(0)
    , ind(0)
    , mrl(0)  {
  (void)_alloc;
    }



   typedef int16_t _thu_type;
  _thu_type thu;

   typedef int16_t _ind_type;
  _ind_type ind;

   typedef int16_t _mrl_type;
  _mrl_type mrl;





  typedef boost::shared_ptr< ::mia_hand_msgs::FingersData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mia_hand_msgs::FingersData_<ContainerAllocator> const> ConstPtr;

}; // struct FingersData_

typedef ::mia_hand_msgs::FingersData_<std::allocator<void> > FingersData;

typedef boost::shared_ptr< ::mia_hand_msgs::FingersData > FingersDataPtr;
typedef boost::shared_ptr< ::mia_hand_msgs::FingersData const> FingersDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mia_hand_msgs::FingersData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mia_hand_msgs::FingersData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mia_hand_msgs::FingersData_<ContainerAllocator1> & lhs, const ::mia_hand_msgs::FingersData_<ContainerAllocator2> & rhs)
{
  return lhs.thu == rhs.thu &&
    lhs.ind == rhs.ind &&
    lhs.mrl == rhs.mrl;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mia_hand_msgs::FingersData_<ContainerAllocator1> & lhs, const ::mia_hand_msgs::FingersData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mia_hand_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mia_hand_msgs::FingersData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mia_hand_msgs::FingersData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mia_hand_msgs::FingersData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "67f7588122a2649383b5219661ab68d4";
  }

  static const char* value(const ::mia_hand_msgs::FingersData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x67f7588122a26493ULL;
  static const uint64_t static_value2 = 0x83b5219661ab68d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mia_hand_msgs/FingersData";
  }

  static const char* value(const ::mia_hand_msgs::FingersData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 thu\n"
"int16 ind\n"
"int16 mrl\n"
;
  }

  static const char* value(const ::mia_hand_msgs::FingersData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.thu);
      stream.next(m.ind);
      stream.next(m.mrl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FingersData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mia_hand_msgs::FingersData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mia_hand_msgs::FingersData_<ContainerAllocator>& v)
  {
    s << indent << "thu: ";
    Printer<int16_t>::stream(s, indent + "  ", v.thu);
    s << indent << "ind: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ind);
    s << indent << "mrl: ";
    Printer<int16_t>::stream(s, indent + "  ", v.mrl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIA_HAND_MSGS_MESSAGE_FINGERSDATA_H
