// Generated by gencpp from file mia_hand_msgs/GetModeRequest.msg
// DO NOT EDIT!


#ifndef MIA_HAND_MSGS_MESSAGE_GETMODEREQUEST_H
#define MIA_HAND_MSGS_MESSAGE_GETMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mia_hand_msgs
{
template <class ContainerAllocator>
struct GetModeRequest_
{
  typedef GetModeRequest_<ContainerAllocator> Type;

  GetModeRequest_()
    {
    }
  GetModeRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetModeRequest_

typedef ::mia_hand_msgs::GetModeRequest_<std::allocator<void> > GetModeRequest;

typedef boost::shared_ptr< ::mia_hand_msgs::GetModeRequest > GetModeRequestPtr;
typedef boost::shared_ptr< ::mia_hand_msgs::GetModeRequest const> GetModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mia_hand_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mia_hand_msgs::GetModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mia_hand_msgs/GetModeRequest";
  }

  static const char* value(const ::mia_hand_msgs::GetModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mia_hand_msgs::GetModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mia_hand_msgs::GetModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mia_hand_msgs::GetModeRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MIA_HAND_MSGS_MESSAGE_GETMODEREQUEST_H
