// Generated by gencpp from file mia_hand_msgs/GetModeResponse.msg
// DO NOT EDIT!


#ifndef MIA_HAND_MSGS_MESSAGE_GETMODERESPONSE_H
#define MIA_HAND_MSGS_MESSAGE_GETMODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mia_hand_msgs
{
template <class ContainerAllocator>
struct GetModeResponse_
{
  typedef GetModeResponse_<ContainerAllocator> Type;

  GetModeResponse_()
    : mode(0)  {
    }
  GetModeResponse_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NORMAL_OPERATION)
  #undef NORMAL_OPERATION
#endif
#if defined(_WIN32) && defined(PAUSED)
  #undef PAUSED
#endif

  enum {
    NORMAL_OPERATION = 0u,
    PAUSED = 1u,
  };


  typedef boost::shared_ptr< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetModeResponse_

typedef ::mia_hand_msgs::GetModeResponse_<std::allocator<void> > GetModeResponse;

typedef boost::shared_ptr< ::mia_hand_msgs::GetModeResponse > GetModeResponsePtr;
typedef boost::shared_ptr< ::mia_hand_msgs::GetModeResponse const> GetModeResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator1> & lhs, const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator1> & lhs, const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mia_hand_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfda0693d1611db496d948702503f0f4";
  }

  static const char* value(const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfda0693d1611db4ULL;
  static const uint64_t static_value2 = 0x96d948702503f0f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mia_hand_msgs/GetModeResponse";
  }

  static const char* value(const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 NORMAL_OPERATION = 0\n"
"uint8 PAUSED = 1\n"
"\n"
"uint8 mode\n"
"\n"
;
  }

  static const char* value(const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mia_hand_msgs::GetModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mia_hand_msgs::GetModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIA_HAND_MSGS_MESSAGE_GETMODERESPONSE_H
