// Generated by gencpp from file mia_hand_msgs/GetMode.msg
// DO NOT EDIT!


#ifndef MIA_HAND_MSGS_MESSAGE_GETMODE_H
#define MIA_HAND_MSGS_MESSAGE_GETMODE_H

#include <ros/service_traits.h>


#include <mia_hand_msgs/GetModeRequest.h>
#include <mia_hand_msgs/GetModeResponse.h>


namespace mia_hand_msgs
{

struct GetMode
{

typedef GetModeRequest Request;
typedef GetModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMode
} // namespace mia_hand_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mia_hand_msgs::GetMode > {
  static const char* value()
  {
    return "bfda0693d1611db496d948702503f0f4";
  }

  static const char* value(const ::mia_hand_msgs::GetMode&) { return value(); }
};

template<>
struct DataType< ::mia_hand_msgs::GetMode > {
  static const char* value()
  {
    return "mia_hand_msgs/GetMode";
  }

  static const char* value(const ::mia_hand_msgs::GetMode&) { return value(); }
};


// service_traits::MD5Sum< ::mia_hand_msgs::GetModeRequest> should match
// service_traits::MD5Sum< ::mia_hand_msgs::GetMode >
template<>
struct MD5Sum< ::mia_hand_msgs::GetModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mia_hand_msgs::GetMode >::value();
  }
  static const char* value(const ::mia_hand_msgs::GetModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mia_hand_msgs::GetModeRequest> should match
// service_traits::DataType< ::mia_hand_msgs::GetMode >
template<>
struct DataType< ::mia_hand_msgs::GetModeRequest>
{
  static const char* value()
  {
    return DataType< ::mia_hand_msgs::GetMode >::value();
  }
  static const char* value(const ::mia_hand_msgs::GetModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mia_hand_msgs::GetModeResponse> should match
// service_traits::MD5Sum< ::mia_hand_msgs::GetMode >
template<>
struct MD5Sum< ::mia_hand_msgs::GetModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mia_hand_msgs::GetMode >::value();
  }
  static const char* value(const ::mia_hand_msgs::GetModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mia_hand_msgs::GetModeResponse> should match
// service_traits::DataType< ::mia_hand_msgs::GetMode >
template<>
struct DataType< ::mia_hand_msgs::GetModeResponse>
{
  static const char* value()
  {
    return DataType< ::mia_hand_msgs::GetMode >::value();
  }
  static const char* value(const ::mia_hand_msgs::GetModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIA_HAND_MSGS_MESSAGE_GETMODE_H
