(cl:defpackage mia_hand_msgs-srv
  (:use )
  (:export
   "CONNECTSERIAL"
   "<CONNECTSERIAL-REQUEST>"
   "CONNECTSERIAL-REQUEST"
   "<CONNECTSERIAL-RESPONSE>"
   "CONNECTSERIAL-RESPONSE"
   "GETMODE"
   "<GETMODE-REQUEST>"
   "GETMODE-REQUEST"
   "<GETMODE-RESPONSE>"
   "GETMODE-RESPONSE"
  ))

